version: '3.8'

services:
  quantumshield:
    build:
      context: .
      dockerfile: docker/quantumshield.Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
      - weaviate

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8081:8081"

volumes:
  postgres_data:
